session格納成功、requestの型、拡張もできた
amanojs/eyesite pull request #7
Opened 2021-07-02 10:53 UTC by kotoso1017

sessionのチェックはまだできてないけどもうほとんど構想はあるのでたぶんできます。

2021-07-02 12:26 UTC, amanojs requested changes
ちゃんと調べながら慎重に、きれいにつくっていってくれているのを感じます 👍🏻 
sessionなど新しいことへの挑戦、難しいところもあると思うけどこの調子なら乗り越えていけると思います！

1つだけ修正点を出したのでそこだけ修正してもう一度プルリクエストをお願いします！

2021-07-02 12:26 UTC, amanojs commented on server.ts
> +require('dotenv').config({ debug: true });
👍🏻

2021-07-02 12:26 UTC, amanojs commented on server.ts
> +}
セッションの中の型の定義だね

2021-07-02 12:26 UTC, amanojs commented on server.ts
> +  if (resultLen > 0) {
(修正点) この if文 の中で result.length を直接比較してもいい気がする！

2021-07-02 12:26 UTC, amanojs commented on server.ts
> +}
勉強になります

2021-07-02 13:33 UTC, kotoso1017 commented on server.ts
> +require('dotenv').config({ debug: true });
連携治せました・・・

2021-07-02 13:35 UTC, kotoso1017 commented on server.ts
> +}
田辺君に教えてもらいました・・・

2021-07-02 13:37 UTC, kotoso1017 commented on server.ts
> +  if (resultLen > 0) {
やってみます～

2021-07-07 07:35 UTC, amanojs approved these changes
おつかれさまです！

2021-07-07 07:35 UTC, merged